import { planAddItem } from "@/lib/add-item";
import { findAsset } from "@/lib/asset-lookup";
import { loadAssetRecords } from "@/lib/asset-sheet";
import { requireRole } from "@/lib/authz";
import { getStore } from "@/lib/store";
import { istTimestamp } from "@/lib/time";
import { randomUUID } from "crypto";
import { redirect } from "next/navigation";

/** Register a new card and save its extra details in attributes JSON. */
export async function addItem(formData: FormData) {
  const user = await requireRole("admin", "im");

  const capacity = String(formData.get("capacity") ?? "").trim();
  const cardType = String(formData.get("cardType") ?? "").trim();
  const rawPrice = String(formData.get("price") ?? "").trim();

  function reject(message: string): never {
    redirect(
      `/inventory?${new URLSearchParams({ addError: message })}`
    );
  }

  if (capacity && !["256 GB", "512 GB"].includes(capacity)) {
    reject("Capacity must be 256 GB or 512 GB.");
  }

  if (cardType && !["Black", "Green"].includes(cardType)) {
    reject("Card type must be Black or Green.");
  }

  if (
    rawPrice &&
    (!/^\d+(?:\.\d{1,2})?$/.test(rawPrice) ||
      !Number.isFinite(Number(rawPrice)))
  ) {
    reject("Enter a valid non-negative price with up to two decimal places.");
  }

  const input = {
    itemId: String(formData.get("itemId") ?? ""),
    homeHub: String(formData.get("homeHub") ?? ""),
    prismNo: String(formData.get("prismNo") ?? ""),
    brand: String(formData.get("brand") ?? ""),
    model: String(formData.get("model") ?? ""),
    price: rawPrice,
  };

  const store = getStore();

  const [items, hubs] = await Promise.all([
    store.list("items"),
    store.list("hubs"),
  ]);

  const plan = planAddItem(input, items, {
    hubs,
    by: user.email ?? "unknown",
    now: istTimestamp(),
    newId: (prefix) => `${prefix}-${randomUUID().slice(0, 8)}`,
  });

  if (plan.errors.length) {
    reject(plan.errors.join(" "));
  }

  if (!plan.item || !plan.event) {
    reject("The item could not be prepared. Nothing was saved.");
  }

  const item = plan.item!;
  const event = plan.event!;

  // Preserve attributes already generated by planAddItem.
  let attributes: Record<string, unknown> = {};

  if (item.attributes?.trim()) {
    try {
      const parsed: unknown = JSON.parse(item.attributes);

      if (
        parsed === null ||
        typeof parsed !== "object" ||
        Array.isArray(parsed)
      ) {
        reject("Invalid item attributes. Nothing was saved.");
      }

      attributes = parsed as Record<string, unknown>;
    } catch {
      reject("Could not read item attributes. Nothing was saved.");
    }
  }

  const itemToSave = {
    ...item,

    // Ensure the submitted amount reaches the existing price column.
    price: rawPrice,

    attributes: JSON.stringify({
      ...attributes,
      capacity,
      card_type: cardType,
    }),
  };

  await store.commitBatch([event], [itemToSave]);

  redirect(
    `/inventory?${new URLSearchParams({
      added: itemToSave.item_id,
    })}`
  );
}

/** Auto-fill a card using its Asset Tag. */
export async function lookupAsset(serial: string) {
  await requireRole("admin", "im");

  const records = await loadAssetRecords();
  const found = findAsset(records, serial);

  return found
    ? {
        brand: found.brand,
        model: found.model,
        prismNo: found.prismNo,
        price: found.price,
        capacity: found.capacity ?? "",
        cardType: found.cardType ?? "",
      }
    : null;
}